#!/usr/bin/env python

import sys
import os
import tempfile

from util.files import write_to_file, write_json_to_file

html_template = """
<!DOCTYPE html>
<html>
<head>
	<title>
		Packj security audit report
	</title>
</head>
<body>
	<div>
		<h4>Security audit report for {{ pkg_name }} (version {{ ver_str }}) generated by <a href="https://github.com/ossillate-inc/packj" target="_blank">Packj</a></h4>
	</div>
	<details>
		<summary><h4>{{ risks | length }} issues found with dependencies. Click for details</h4></summary>
		<table style="border-style: solid; border-width: thin;">
			<tr>
				<th>Risk</th>
				<th>Reason</th>
				<th>Details</th>
			</tr>
			{% for r in risks %}
				<tr>
					<td>{{ r.0 }}</td>
					<td>{{ r.1 }}</td>
					<td>{{ r.2 }}</td>
				</tr>
			{% endfor %}
		</table>
	</details>
	<div>
		<h4>Powered by <a href="https://ossillate.com" target="_blank">Ossillate</a></h4>
	</div>
</body>
</html>
"""

def create_html_report(report, filepath):

	from django.conf import settings
	TEMPLATES = [{'BACKEND':  'django.template.backends.django.DjangoTemplates'}]
	settings.configure(TEMPLATES=TEMPLATES)
	
	import django
	django.setup()
	
	from django.template import Template, Context

	total_risks = len(report['risks'])
	report_title = f'Packj security audit report'

	risk_list = []
	for category, risks in report['risks'].items():
		for item in risks:
			reason, details = str(item).strip(' ').split(':')
			risk_list.append((category, reason, details))

	t = Template(html_template)
	c = Context({"title": report_title, "risks": risk_list})

	write_to_file(filepath, t.render(c))

def generate_report(report, args, suffix='.json'):

	container_mountpoint, report_dir = args

	print('=============================================')

	_, filepath = tempfile.mkstemp(prefix=f'report_', dir=report_dir, suffix=suffix)
	if suffix == '.json':
		write_json_to_file(filepath, report, indent=4)
	else:
		create_html_report(report, filepath)
		
	os.chmod(filepath, 0o444)
	if container_mountpoint:
		filepath = filepath.replace(container_mountpoint, host_volume)
	print(f'=> Complete report: {filepath}')
