# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\ninfo.proto\x12\x05proto\".\n\x0bReleaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"+\n\x0eRepositoryInfo\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\".\n\x0b\x45xecuteInfo\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\xc4\x03\n\x0bPackageInfo\x12)\n\x04info\x18\x01 \x01(\x0b\x32\x1b.proto.PackageInfo.Metadata\x12\x31\n\x0c\x64\x65pendencies\x18\x02 \x03(\x0b\x32\x1b.proto.PackageInfo.Metadata\x12\x35\n\x10\x64\x65v_dependencies\x18\x03 \x03(\x0b\x32\x1b.proto.PackageInfo.Metadata\x1a\x9f\x02\n\x08Metadata\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x17\n\x0fpackage_version\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08homepage\x18\x04 \x01(\t\x12\x0f\n\x07license\x18\x05 \x01(\t\x12)\n\nrepository\x18\x06 \x01(\x0b\x32\x15.proto.RepositoryInfo\x12%\n\texec_jobs\x18\x07 \x03(\x0b\x32\x12.proto.ExecuteInfo\x12\x0f\n\x07\x61uthors\x18\x08 \x03(\t\x12\x14\n\x0c\x63ontributors\x18\t \x03(\t\x12\x13\n\x0bmaintainers\x18\n \x03(\t\x12$\n\x08releases\x18\x0b \x03(\x0b\x32\x12.proto.ReleaseInfob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RELEASEINFO = _descriptor.Descriptor(
  name='ReleaseInfo',
  full_name='proto.ReleaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.ReleaseInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.ReleaseInfo.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=67,
)


_REPOSITORYINFO = _descriptor.Descriptor(
  name='RepositoryInfo',
  full_name='proto.RepositoryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='proto.RepositoryInfo.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.RepositoryInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=112,
)


_EXECUTEINFO = _descriptor.Descriptor(
  name='ExecuteInfo',
  full_name='proto.ExecuteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='proto.ExecuteInfo.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='proto.ExecuteInfo.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=160,
)


_PACKAGEINFO_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='proto.PackageInfo.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_name', full_name='proto.PackageInfo.Metadata.package_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='package_version', full_name='proto.PackageInfo.Metadata.package_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='proto.PackageInfo.Metadata.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='homepage', full_name='proto.PackageInfo.Metadata.homepage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='license', full_name='proto.PackageInfo.Metadata.license', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repository', full_name='proto.PackageInfo.Metadata.repository', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_jobs', full_name='proto.PackageInfo.Metadata.exec_jobs', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authors', full_name='proto.PackageInfo.Metadata.authors', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contributors', full_name='proto.PackageInfo.Metadata.contributors', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maintainers', full_name='proto.PackageInfo.Metadata.maintainers', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='releases', full_name='proto.PackageInfo.Metadata.releases', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=615,
)

_PACKAGEINFO = _descriptor.Descriptor(
  name='PackageInfo',
  full_name='proto.PackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='proto.PackageInfo.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='proto.PackageInfo.dependencies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dev_dependencies', full_name='proto.PackageInfo.dev_dependencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PACKAGEINFO_METADATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=615,
)

_PACKAGEINFO_METADATA.fields_by_name['repository'].message_type = _REPOSITORYINFO
_PACKAGEINFO_METADATA.fields_by_name['exec_jobs'].message_type = _EXECUTEINFO
_PACKAGEINFO_METADATA.fields_by_name['releases'].message_type = _RELEASEINFO
_PACKAGEINFO_METADATA.containing_type = _PACKAGEINFO
_PACKAGEINFO.fields_by_name['info'].message_type = _PACKAGEINFO_METADATA
_PACKAGEINFO.fields_by_name['dependencies'].message_type = _PACKAGEINFO_METADATA
_PACKAGEINFO.fields_by_name['dev_dependencies'].message_type = _PACKAGEINFO_METADATA
DESCRIPTOR.message_types_by_name['ReleaseInfo'] = _RELEASEINFO
DESCRIPTOR.message_types_by_name['RepositoryInfo'] = _REPOSITORYINFO
DESCRIPTOR.message_types_by_name['ExecuteInfo'] = _EXECUTEINFO
DESCRIPTOR.message_types_by_name['PackageInfo'] = _PACKAGEINFO

ReleaseInfo = _reflection.GeneratedProtocolMessageType('ReleaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _RELEASEINFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:proto.ReleaseInfo)
  ))
_sym_db.RegisterMessage(ReleaseInfo)

RepositoryInfo = _reflection.GeneratedProtocolMessageType('RepositoryInfo', (_message.Message,), dict(
  DESCRIPTOR = _REPOSITORYINFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:proto.RepositoryInfo)
  ))
_sym_db.RegisterMessage(RepositoryInfo)

ExecuteInfo = _reflection.GeneratedProtocolMessageType('ExecuteInfo', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEINFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:proto.ExecuteInfo)
  ))
_sym_db.RegisterMessage(ExecuteInfo)

PackageInfo = _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), dict(

  Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), dict(
    DESCRIPTOR = _PACKAGEINFO_METADATA,
    __module__ = 'info_pb2'
    # @@protoc_insertion_point(class_scope:proto.PackageInfo.Metadata)
    ))
  ,
  DESCRIPTOR = _PACKAGEINFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:proto.PackageInfo)
  ))
_sym_db.RegisterMessage(PackageInfo)
_sym_db.RegisterMessage(PackageInfo.Metadata)


# @@protoc_insertion_point(module_scope)
