# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

require 'google/protobuf'

require 'info_pb'
require 'module_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.NetworkActivity" do
    optional :domain, :string, 1
    optional :url, :string, 2
    optional :ip, :string, 3
    optional :port, :int32, 4
    optional :protocol, :string, 5
    optional :send_content, :string, 6
    optional :send_content_size, :int32, 7
    optional :receive_content, :string, 8
    optional :receive_content_size, :int32, 9
  end
  add_message "proto.FileActivity" do
    optional :filename, :string, 1
    optional :filepath, :string, 2
    optional :mode, :string, 3
    optional :permission, :string, 4
    optional :read_content, :string, 5
    optional :read_content_size, :string, 6
    optional :add_content, :string, 7
    optional :add_content_size, :int32, 8
    optional :remove_content, :string, 9
    optional :remove_content_size, :int32, 10
    optional :modify_content, :string, 11
    optional :modify_content_size, :int32, 12
  end
  add_message "proto.SensitivenActivity" do
    optional :pid, :string, 1
    optional :cmdline, :string, 2
    optional :exe, :string, 3
    optional :cwd, :string, 4
    optional :root, :string, 5
    optional :ppid, :string, 6
    optional :user, :string, 7
    optional :syscall, :string, 8
  end
  add_message "proto.ProcessActivity" do
    optional :pid, :string, 1
    optional :cmdline, :string, 2
    optional :exe, :string, 3
    optional :cwd, :string, 4
    optional :root, :string, 5
    optional :ppid, :string, 6
    optional :user, :string, 7
    optional :permission, :string, 8
    optional :main_process, :bool, 9
    repeated :network_activities, :message, 10, "proto.NetworkActivity"
    repeated :file_activities, :message, 11, "proto.FileActivity"
    repeated :child_process_activities, :message, 12, "proto.ProcessActivity"
    repeated :sensitive_activities, :message, 13, "proto.SensitivenActivity"
  end
  add_message "proto.DynamicAnalysis" do
    optional :analysis_type, :enum, 1, "proto.AnalysisType"
    optional :exe_type, :enum, 2, "proto.ExecutionType"
    optional :exe_user, :string, 3
    optional :timestamp, :string, 4
    optional :end_timestamp, :string, 5
    optional :process_activity, :message, 6, "proto.ProcessActivity"
  end
  add_message "proto.StaticAnalysis" do
    optional :analysis_type, :enum, 1, "proto.AnalysisType"
    optional :timestamp, :string, 2
    optional :code_activity, :message, 3, "proto.ModuleStatic"
  end
  add_message "proto.ConcolicAnalysis" do
    optional :analysis_type, :enum, 1, "proto.AnalysisType"
    optional :exe_type, :enum, 2, "proto.ExecutionType"
    optional :exe_user, :string, 3
    optional :timestamp, :string, 4
    optional :end_timestamp, :string, 5
    optional :process_activity, :message, 6, "proto.ProcessActivity"
  end
  add_message "proto.AnalysisResult" do
    optional :package_info, :message, 1, "proto.PackageInfo"
    repeated :dynamic_results, :message, 2, "proto.DynamicAnalysis"
    repeated :static_results, :message, 3, "proto.StaticAnalysis"
    repeated :concolic_results, :message, 4, "proto.ConcolicAnalysis"
  end
  add_enum "proto.ExecutionType" do
    value :INSTALL, 0
    value :MAIN, 1
    value :EXERCISE, 2
    value :TEST, 3
  end
  add_enum "proto.AnalysisType" do
    value :API_USAGE, 0
    value :REACHABILITY, 1
    value :TAINT_TRACKING, 2
    value :SYMBOLIC, 3
  end
end

module Proto
  NetworkActivity = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NetworkActivity").msgclass
  FileActivity = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.FileActivity").msgclass
  SensitivenActivity = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SensitivenActivity").msgclass
  ProcessActivity = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ProcessActivity").msgclass
  DynamicAnalysis = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DynamicAnalysis").msgclass
  StaticAnalysis = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.StaticAnalysis").msgclass
  ConcolicAnalysis = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ConcolicAnalysis").msgclass
  AnalysisResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AnalysisResult").msgclass
  ExecutionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ExecutionType").enummodule
  AnalysisType = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AnalysisType").enummodule
end
