# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.ReleaseInfo" do
    optional :name, :string, 1
    optional :timestamp, :string, 2
  end
  add_message "proto.RepositoryInfo" do
    optional :url, :string, 1
    optional :type, :string, 2
  end
  add_message "proto.ExecuteInfo" do
    optional :target, :string, 1
    optional :command, :string, 2
  end
  add_message "proto.PackageInfo" do
    optional :info, :message, 1, "proto.PackageInfo.Metadata"
    repeated :dependencies, :message, 2, "proto.PackageInfo.Metadata"
    repeated :dev_dependencies, :message, 3, "proto.PackageInfo.Metadata"
  end
  add_message "proto.PackageInfo.Metadata" do
    optional :package_name, :string, 1
    optional :package_version, :string, 2
    optional :email, :string, 3
    optional :homepage, :string, 4
    optional :license, :string, 5
    optional :repository, :message, 6, "proto.RepositoryInfo"
    repeated :exec_jobs, :message, 7, "proto.ExecuteInfo"
    repeated :authors, :string, 8
    repeated :contributors, :string, 9
    repeated :maintainers, :string, 10
    repeated :releases, :message, 11, "proto.ReleaseInfo"
  end
end

module Proto
  ReleaseInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ReleaseInfo").msgclass
  RepositoryInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.RepositoryInfo").msgclass
  ExecuteInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ExecuteInfo").msgclass
  PackageInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.PackageInfo").msgclass
  PackageInfo::Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.PackageInfo.Metadata").msgclass
end
